# Generated by Django 4.2.2 on 2023-06-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("in progress", "In Progress"),
                            ("planned", "Planned"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
