# Generated by Django 4.2.2 on 2023-06-16 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "story_id",
                    models.IntegerField(
                        choices=[
                            (1, "Alice in Wonderland"),
                            (2, "Beauty and the Beast"),
                            (3, "Christmas Carol"),
                            (4, "Cinderella"),
                            (5, "Snow White and the Seven Dwarfs"),
                            (6, "Little Red Riding Hood"),
                            (7, "Sleeping Beauty"),
                            (8, "Rapunzel"),
                            (9, "Rumplestiltskin"),
                            (10, "Jack and the Beanstalk"),
                            (11, "The Legend of the Sleepy Hollow"),
                            (12, "Peter Pan"),
                            (13, "Phantom of the Opera"),
                            (14, "Winnie the Pooh"),
                            (15, "The Wizard of Oz"),
                            (16, "Treasure Island"),
                            (17, "The Little Mermaid"),
                            (18, "The Ugly Duckling"),
                            (19, "Thumbelina"),
                            (20, "Hansel and Gretel"),
                            (21, "The Emperor's New Suit"),
                            (22, "Puss in Boots"),
                            (23, "Goldilocks"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPrompts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.story"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.TextField()),
                (
                    "prompt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.userprompts",
                    ),
                ),
            ],
        ),
    ]
